version: '3'

services:
    db:
        image: postgres:11
        ports:
            - 32700:5432
        volumes:
            ./db_data:/var/lib/postgresql/db_data
        environment:
            POSTGRES_USER:  root
            POSTGRES_PASSWORD:  rootpassword
            POSTGRES_DB: todoapp