"""Added library models

Revision ID: 577336ea467c
Revises: 5c1f98c760d0
Create Date: 2021-06-15 15:32:30.448235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577336ea467c'
down_revision = '5c1f98c760d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
