"""Added Relation

Revision ID: 5c1f98c760d0
Revises: 4e4abb3edbda
Create Date: 2021-06-11 16:24:48.198803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1f98c760d0'
down_revision = '4e4abb3edbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
