"""Added in todo table prop2 

Revision ID: 76dc21ef5c50
Revises: e10b30cb52e5
Create Date: 2021-06-10 11:27:37.240931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76dc21ef5c50'
down_revision = 'e10b30cb52e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
