"""Added in todo table prop 

Revision ID: e10b30cb52e5
Revises: 721c23f93b06
Create Date: 2021-06-10 09:27:08.645162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10b30cb52e5'
down_revision = '721c23f93b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
